### ISSUE TITLE
[Bug]: calling the CLI with --version or --help crashes

### ISSUE THREAD

**Issue by woodcoder** [Green-Software-Foundation/carbon-aware-sdk#166]
### Contact Details

andy@bitshaper.co.uk

### What happened?

Using v1.0.0, running the cli with `--version` or `--help` crashes with an unhandled exception.

```
cd src/CarbonAware.CLI/src
dotnet run --version
dotnet run -- --help
```

It does output the version or help text first, so this is not the most important of bugs, so no need to rush to fix!

### client

CLI

### Relevant log output

```shell
bin/Release/net6.0/publish/CarbonAware.CLI --version
CarbonAware.CLI 1.0.0
Unhandled exception. System.ArgumentException: Invalid parameters
   at CarbonAware.Aggregators.CarbonAware.CarbonAwareParameters.AssertNoErrors(Dictionary`2 errors) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareParameters.cs:line 305
   at CarbonAware.Aggregators.CarbonAware.CarbonAwareParameters.Validate() in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareParameters.cs:line 184
   at CarbonAware.Aggregators.CarbonAware.CarbonAwareAggregator.GetEmissionsDataAsync(CarbonAwareParameters parameters) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareAggregator.cs:line 35
   at CarbonAware.CLI.CarbonAwareCLI.GetEmissions() in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.CLI/src/CarbonAwareCLI.cs:line 76
   at CarbonAware.CLI.Program.GetEmissionsAsync(String[] args, ICarbonAwareAggregator aggregator, ILogger`1 logger) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.CLI/src/Program.cs:line 42
   at CarbonAware.CLI.Program.Main(String[] args) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.CLI/src/Program.cs:line 15
   at CarbonAware.CLI.Program.<Main>(String[] args)
Aborted (core dumped)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esgraham** [comment]
This issue was addressed and resolved in pull request: Carbon Aware CLI redesign https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/158
