### ISSUE TITLE
[Bug]: DataSources state in environment variables is not respected in WebAPI

### ISSUE THREAD

**Issue by markvideon** [Green-Software-Foundation/carbon-aware-sdk#230]
### Contact Details

hello@markvideon.dev

### What happened?

DataSources information in environment variables at runtime are not respected. Specifying DataSources information in appsettings.json _is_ respected as one would expect.

Instructions to reproduce:

1. Following the [Getting Started guide](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/GettingStarted.md), building a container for the Web API, with the tag `carbon-aware-sdk-webapi`. 
2. Running the container:
```
docker run -it --rm -p 8080:80 \
    -e DataSources__EmissionsDataSource="WattTime" \
    -e DataSources__ForecastDataSource="WattTime" \
    -e DataSources__Configurations__WattTime__Username=YOUR_USERNAME \
    -e DataSources__Configurations__WattTime__Password=YOUR_PASSWORD \
  carbon-aware-sdk-webapi
```

3. Performing a CURL request:
```
curl "http://localhost:8080/emissions/bylocations/best?location=YOUR_LOCATION&time=2022-05-25&toTime=2022-05-26&durationMinutes=0"
```

### client

WebAPI (Default)

### Relevant log output

```shell
CarbonAware.WebApi.Filters.HttpResponseExceptionFilter[0]
      Exception: EmissionsDataSource is not configured
      System.ArgumentException: EmissionsDataSource is not configured
         at CarbonAware.NullEmissionsDataSource.GetCarbonIntensityAsync(IEnumerable`1 locations, DateTimeOffset periodStartTime, DateTimeOffset periodEndTime) in /app/CarbonAware/src/NullEmissionsDataSource.cs:line 9
         at CarbonAware.Aggregators.Emissions.EmissionsAggregator.GetBestEmissionsDataAsync(CarbonAwareParameters parameters) in /app/CarbonAware.Aggregators/src/Emissions/EmissionsAggregator.cs:line 56
         at CarbonAware.WebApi.Controllers.CarbonAwareController.GetBestEmissionsDataForLocationsByTime(EmissionsDataForLocationsParametersDTO parameters) in /app/CarbonAware.WebApi/src/Controllers/CarbonAwareController.cs:line 44
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FabioTurati-NTT** [comment]
This is a problem with the documentation, not with the code. When you launch the container you have to set one more variable to make it work: you need to add `    -e DataSources__Configurations__WattTime__Type="WattTime" \`. Like this:

```
podman run -it --rm -p 8080:80 \
    -e DataSources__EmissionsDataSource="WattTime" \
    -e DataSources__ForecastDataSource="WattTime" \
    -e DataSources__Configurations__WattTime__Type="WattTime" \
    -e DataSources__Configurations__WattTime__Username=YOUR_USERNAME \
    -e DataSources__Configurations__WattTime__Password=YOUR_PASSWORD \
  carbon-aware-sdk-webapi
```

This variable is correctly reported at [quickstart.md][2] but it's missing from [GettingStarted.md][2].

  [1]: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md
  [2]: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/GettingStarted.md

**Comment by Willmish** [comment]
Thanks for covering this @FabioTurati-NTT , seems like the next issue to tackle around this is to consolidate the documentation once more. Opening https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/259 to reflect this.

**Comment by Willmish** [comment]
Can you confirm @markvideon adding the variable  `-e DataSources__Configurations__WattTime__Type="WattTime"` solved your issue?

**Comment by markvideon** [comment]
> Can you confirm @markvideon adding the variable `-e DataSources__Configurations__WattTime__Type="WattTime"` solved your issue?

Just had a go. Unfortunately I can not. Looks like my WattTime credentials have been disabled.

**Comment by markvideon** [comment]
> > Can you confirm @markvideon adding the variable `-e DataSources__Configurations__WattTime__Type="WattTime"` solved your issue?
> 
> Just had a go. Unfortunately I can not. Looks like my WattTime credentials have been disabled.

@Willmish I made the above comment after receiving this response:

{"title":"WattTimeClientHttpException","status":403,"detail":"Login failed for user: 'gsf_mark.videon'","traceId":"00-c1ee03451528a431b684183a0c9160f6-d48a42ef09884539-00","errors":{}}  

However I'm able to retrieve a login token from the WattTime API directly with my credentials. There may be some kind of authentication issue within the carbon aware SDK...

**Comment by Willmish** [comment]
Closed in the commit https://github.com/Green-Software-Foundation/carbon-aware-sdk/commit/6fbd924a5e77f2ff85bed4490e8324079eaef5bc
