### ISSUE TITLE
[Bug]: Generating SDK client does not work on linux

### ISSUE THREAD

**Issue by MartinDawson** [Green-Software-Foundation/carbon-aware-sdk#232]
### What happened?

Following the docs here: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md

> ./docker-generate-clients.sh host.docker.internal:5073
rm: cannot remove './javascript': No such file or directory
[main] ERROR io.swagger.v3.parser.util.RemoteUrl - unable to read
java.net.UnknownHostException: host.docker.internal
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClie

Probably something to do with this? https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
Hi and thanks for raising the issue @MartinDawson  - are you able to share the exact command you have ran?

From what I've seen you are right that accessing host's ports from within a docker container via `host.docker.internal` is supported only on Mac and Windows. The docs in [quickstart.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md) need to be consolidated with the guide within (src/clients)[https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev/src/clients#generate] directory, or directly refer to it. Can you check if this issue persists if you try following that one instead?
