### ISSUE TITLE
[Bug]: Documentation improvement possibilities: Configurations

### ISSUE THREAD

**Issue by tmcclell** [Green-Software-Foundation/carbon-aware-sdk#325]
### Contact Details

tmcclell@microsoft.com

### What happened?

A bug happened! Did a pull from a recently sync fork, build and run and hit this error. I didn't see any documentation on how to set up datasources, but WattTime is listed in Configurations.

### client

WebAPI (Default)

### Relevant log output

```shell
System.ArgumentException
  HResult=0x80070057
  Message=Emissions data source value 'WattTime' was not found in 'Configurations'
  Source=CarbonAware
  StackTrace:
   at CarbonAware.Configuration.DataSourcesConfiguration.AssertValid() in C:\Users\tmcclell\Documents\Source\carbon-aware-sdk-dev\carbon-aware-sdk-dev\src\src\CarbonAware\src\Configuration\DataSourcesConfiguration.cs:line 61
   at CarbonAware.Configuration.DataSourcesConfigurationExtensions.DataSources(IConfiguration configuration) in C:\Users\tmcclell\Documents\Source\carbon-aware-sdk-dev\carbon-aware-sdk-dev\src\src\CarbonAware\src\Configuration\DataSourcesConfigurationExtensions.cs:line 11
   at CarbonAware.DataSources.Configuration.ServiceCollectionExtensions.AddDataSourceService(IServiceCollection services, IConfiguration configuration) in C:\Users\tmcclell\Documents\Source\carbon-aware-sdk-dev\carbon-aware-sdk-dev\src\src\CarbonAware.DataSources\CarbonAware.DataSources.Registration\Configuration\ServiceCollectionExtensions.cs:line 16
   at GSF.CarbonAware.Configuration.ServiceCollectionExtensions.AddEmissionsServices(IServiceCollection services, IConfiguration configuration) in C:\Users\tmcclell\Documents\Source\carbon-aware-sdk-dev\carbon-aware-sdk-dev\src\src\GSF.CarbonAware\src\Configuration\ServiceCollectionExtensions.cs:line 24
   at Program.<Main>$(String[] args) in C:\Users\tmcclell\Documents\Source\carbon-aware-sdk-dev\carbon-aware-sdk-dev\src\src\CarbonAware.WebApi\src\Program.cs:line 57
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
Discussed in #328 

The issue was WattTime missing in 'Configurations" section in the appsettings. See this for future reference, might be helpful to add an example with multiple EM configurations set up or WattTime, to show different names in 
`        "EmissionsDataSource": "WattTime",` not just the DataSource types, as the configuration can be any string, e.g.: `"MyWattTimeDataSource"`.

Also might consider moving https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md#configuration-options higher up in overview.md.
https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/configuration.md#configuration-using-watttime-and-defined-location-source-files

**Comment by Willmish** [comment]
Maybe point more clearly to the sample template appsettings.Development.json: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/src/CarbonAware.WebApi/src/appsettings.Development.json.template
