### ISSUE TITLE
[Bug]: Unhandled exception. CarbonAware.Exceptions.ConfigurationException: No data sources are configured

### ISSUE THREAD

**Issue by jacksorjacksor** [Green-Software-Foundation/carbon-aware-sdk#426]
### Contact Details

jacksorjacksor@pm.me

### What happened?

First attempt at running `.\ caw.exe -h` (as per [docs](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/carbon-aware-cli.md)) and received error message.

Prior actions:

- Cloned repo
- Ran `dotnet publish ./src/CarbonAware.CLI/src/CarbonAware.CLI.csproj -c Release -o [outputPath]`
- Ran `.\ caw.exe -h` from `outputPath`
- Error!

Full error log:

```
 CarbonAwareSdk  .\caw.exe -h
Unhandled exception. CarbonAware.Exceptions.ConfigurationException: No data sources are configured
   at CarbonAware.DataSources.Configuration.ServiceCollectionExtensions.AddDataSourceService(IServiceCollection services, IConfiguration configuration) in D:\OneDriveFolders\OneDrive\Documents\Coding\carbon-aware-sdk\src\CarbonAware.DataSources\CarbonAware.DataSources.Registration\Configuration\ServiceCollectionExtensions.cs:line 80
   at GSF.CarbonAware.Configuration.ServiceCollectionExtensions.AddEmissionsServices(IServiceCollection services, IConfiguration configuration) in D:\OneDriveFolders\OneDrive\Documents\Coding\carbon-aware-sdk\src\GSF.CarbonAware\src\Configuration\ServiceCollectionExtensions.cs:line 24
   at Program.<Main>$(String[] args) in D:\OneDriveFolders\OneDrive\Documents\Coding\carbon-aware-sdk\src\CarbonAware.CLI\src\Program.cs:line 31
   at Program.<Main>(String[] args)
```

### client

CLI

### Relevant log output

```shell
 CarbonAwareSdk  .\caw.exe -h
Unhandled exception. CarbonAware.Exceptions.ConfigurationException: No data sources are configured
   at CarbonAware.DataSources.Configuration.ServiceCollectionExtensions.AddDataSourceService(IServiceCollection services, IConfiguration configuration) in D:\OneDriveFolders\OneDrive\Documents\Coding\carbon-aware-sdk\src\CarbonAware.DataSources\CarbonAware.DataSources.Registration\Configuration\ServiceCollectionExtensions.cs:line 80
   at GSF.CarbonAware.Configuration.ServiceCollectionExtensions.AddEmissionsServices(IServiceCollection services, IConfiguration configuration) in D:\OneDriveFolders\OneDrive\Documents\Coding\carbon-aware-sdk\src\GSF.CarbonAware\src\Configuration\ServiceCollectionExtensions.cs:line 24
   at Program.<Main>$(String[] args) in D:\OneDriveFolders\OneDrive\Documents\Coding\carbon-aware-sdk\src\CarbonAware.CLI\src\Program.cs:line 31
   at Program.<Main>(String[] args)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
@YaSuenag can you help double check this (in relation to your PR ? #450 ) please?

**Comment by YaSuenag** [comment]
> @YaSuenag can you help double check this (in relation to your PR ? #450 ) please?

I think it is nature after because the user should configure data source / locations. So I've  proposed #450 to enforce these configurations to the SDK users. If #450 is accepted, this issue can be closed as not a bug.

**Comment by YaSuenag** [comment]
Please keep this issue while #450 is opened. See comments from me in above.

**Comment by YaSuenag** [comment]
Wait! As I said before, I will start to work for this issue after #450 .

**Comment by YaSuenag** [comment]
Sorry for the late for working of this issue.

Now I'm working on #450, we have to configure datasource in any cases because CASDK act like an API gateway - it means the SDK should have datasource(s). The error should be reported if datasource is not configured because the SDK would not return the value which the user does not expect.

I believe #450 would be merged soon. I close this issue after #450.
