### ISSUE TITLE
[Bug]: CLI does not work by default as the WebApi does

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#76]
### What happened?

If you get the latest dev branch (with 0.1-preview changes) and try and run the cli with the below command, the cli errors.

```dotnet run -l eastus westus australiaeast northeurope -t 2021-12-28 --toTime 2021-12-30 -v --lowest ```

Expected:
Using the default parameters, the cli should be able to come back with a default response...

Solution:
Comparing to the WebApi which does work as described above, it must be missing some default values

### client

CLI

### Relevant log output

```shell
info: CarbonAware.Aggregators.CarbonAware.CarbonAwareAggregator[0]
      Aggregator getting carbon intensity from data source
info: CarbonAware.DataSources.WattTime.WattTimeDataSource[0]
      Getting carbon intensity for locations {"locationType":0,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"eastus","displayName":"Not Provided"}, {"locationType":0,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"westus","displayName":"Not Provided"}, {"locationType":0,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"australiaeast","displayName":"Not Provided"}, {"locationType":0,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"northeurope","displayName":"Not Provided"} for period 12/28/2021 00:00:00 +00:00 to 12/30/2021 00:00:00 +00:00.
info: CarbonAware.DataSources.WattTime.WattTimeDataSource[0]
      Getting carbon intensity for location {"locationType":0,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"eastus","displayName":"Not Provided"} for period 28/12/2021 00:00:00 +00:00 to 30/12/2021 00:00:00 +00:00.
fail: CarbonAware.DataSources.WattTime.WattTimeDataSource[0]
      Failed to convert the location {"locationType":0,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"eastus","displayName":"Not Provided"} into a Balancying Authority.
      CarbonAware.Exceptions.LocationConversionException: Location '' cannot be converted to Geoposition. 
         at CarbonAware.LocationSources.Azure.AzureLocationSource.ToGeopositionLocationAsync(Location location) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/src/AzureLocationSource.cs:line 55
         at CarbonAware.DataSources.WattTime.WattTimeDataSource.GetBalancingAuthority(Location location, Activity activity) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs:line 151
Unhandled exception. CarbonAware.Exceptions.LocationConversionException: Location '' cannot be converted to Geoposition. 
   at CarbonAware.LocationSources.Azure.AzureLocationSource.ToGeopositionLocationAsync(Location location) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/src/AzureLocationSource.cs:line 55
   at CarbonAware.DataSources.WattTime.WattTimeDataSource.GetBalancingAuthority(Location location, Activity activity) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs:line 151
   at CarbonAware.DataSources.WattTime.WattTimeDataSource.GetCarbonIntensityAsync(Location location, DateTimeOffset periodStartTime, DateTimeOffset periodEndTime) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs:line 98
   at CarbonAware.DataSources.WattTime.WattTimeDataSource.GetCarbonIntensityAsync(IEnumerable`1 locations, DateTimeOffset periodStartTime, DateTimeOffset periodEndTime) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/WattTimeDataSource.cs:line 57
   at CarbonAware.Aggregators.CarbonAware.CarbonAwareAggregator.GetEmissionsDataAsync(IDictionary props) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareAggregator.cs:line 36
   at CarbonAware.CLI.CarbonAwareCLI.GetEmissionsDataAsync(Dictionary`2 props) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.CLI/src/CarbonAwareCLI.cs:line 73
   at CarbonAware.CLI.CarbonAwareCLI.GetEmissions() in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.CLI/src/CarbonAwareCLI.cs:line 68
   at CarbonAware.CLI.Program.GetEmissionsAsync(String[] args, ICarbonAwareAggregator aggregator, ILogger`1 logger) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.CLI/src/Program.cs:line 41
   at CarbonAware.CLI.Program.Main(String[] args) in /Users/dan.benitah/projects/ava/gsf/carbon-aware-sdk/src/CarbonAware.CLI/src/Program.cs:line 15
   at CarbonAware.CLI.Program.<Main>(String[] args)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
Will close. We can create a new one when we find more but I have no more example anymore.
